### ISSUE TITLE
Error: IAudioClient::Initialize failed: hr = 0x80070005

### ISSUE THREAD

**Issue by public-radiation** [ToadKing/mono-to-stereo#1]
Hi,

I am trying to use your fix for my HDMI Capture card with obs but i keep running in to the following issue:

```
mono-to-stereo.exe --in-device "Digitale audio-interface (2- USB Digital Audio)"
Error: IAudioClient::Initialize failed: hr = 0x80070005
Error: Thread aborted before starting to capture: hr = 0x80070005
```

As far as my googeling goes 0x80070005 can mean acces denied, but i ran the programm in cmd with admin priv. 

I have done a quick run of the loopback capture you mention, that seems to run and create wav file.

So just wanted to let you know, and see if you can help me along. If not its okay. Just would like to use your elegant solution.

I am using a  Dutch version of Windows 10 Home x64 

Any help is welcome. Thank you!

**Comment by ToadKing** [comment]
It's possible some other program has exclusive access to the device. See if you can turn off exclusive mode for that audio device and see if it works.

**Comment by public-radiation** [comment]
Thanks for the quick reply, i checked again on that laptop and made sure all the exclusive boxes where checked of. But it still had the error. I moved to an other laptop and on that machine it does work. The biggest deference between the machines is that one it works on is an English machine, the other one Dutch. Weird, maybe i am missing something else. But i have something working for now. i'll will look in to switching to English on the first laptop see if that helps. But the first laptop isn't mine but from a friend so might take a while.

Again thanks for the software and the support. Have a good day!

**Comment by flextcg** [comment]
Hi public-radiation,

I've had the same problem on my Hungarian Windows as well. 

You'll have to specify the input, and output in your command by listing the devices with the "--list-devices" parameter first. The reason you have to do that is, that the input and output devices in the default command are using the English device names. Once you have them listed, copy and paste the ones you choose to use into your command.

For example: 

mono-to-stereo.exe --in-device "Your HDMI Capture card from the list" --out-device "An output device from the list you want to stream the audio to" --buffer-size 128 --no-skip-first-sample
