### ISSUE TITLE
Request to use this little great tool also for regular stereo devices

### ISSUE THREAD

**Issue by GianlucaApollaro** [ToadKing/mono-to-stereo#11]

**Comment by cehbab** [comment]
This is very delayed, but I've just added this functionality to my fork..
Just been playing with this project for something I needed it for..

**Comment by GianlucaApollaro** [comment]
Wow thanks. I'll test it as soon as I can.

**Comment by GianlucaApollaro** [comment]
It worked flawlessly, I had to use --force-mono-to-stereo to get the behaviour I got with the other version when using the capture cards with the 96000 samplerate mono issue. Understood that, now it works with everything and I have the best of both worlds. Thanks a lot again. Could I make a little request? I happen to have a device that is stereo, but it gets only the right channel as its input, even though it's seen as stereo by windows. Could it be possible to have a downmix command which can downmix both channels to mono? Thanks again for your huge work.

**Comment by cehbab** [comment]
Yes, it now doesn't expect everything to be a stuffed stereo hidden in a mono stream.
and I toggled the name of the parameter from --no-skip to -skip so you have to enable that as well, off by default

I'm working on capturing output audio devices to route them to my other speakers for the fun of it at the moment.

My work is not huge, ToadKing did the work, on top of Matthew van Eerde's work... Its interesting to me though...

**Comment by cehbab** [comment]
To answer your request, its weird doing this under ToadKings repo.. But I will explain
I'm still working on the down mixing part... and its all hacky, there is no understanding of big endian or little endianess, so the actual sample value per channel is unknown.. Im simply copying blocks when upMixing and clearing the remaining channels.

I could easily add a --copy-left-to-right and --copy-right-to-left and then use that if its a stereo capture device, and now also if its a captured stereo render device (im working on that now).   That way if its a mono output, it should be already the value you want, and if its a stereo or higher channel count output device, it should already be ready to go.

**Comment by cehbab** [comment]
downmixing requires averaging things to do it properly, hence I'd need to understand the bytes of each channel sample and add them up, average them, and then get the individual byutes back in the appropriate order little or bi endian, and then store.. and my brain is not coping with that yet.

**Comment by cehbab** [comment]
same for frequency changes, ie 41000 -> 48000 or whatever, involves full on maths, that my brain is also not ready for :)

**Comment by cehbab** [comment]
Updated, also did swap channels.. see the usage..   and I got the reading from output audio devices to feedback to another output device.. its interesting :)...  you can setup feedback loops now, and I thought to detect that and stop it, but its more fun to have it happen if you want it to 
:)

**Comment by GianlucaApollaro** [comment]
Hi, the copy and swap commands don't seem to work, If I copy right to left I get wheird aliased output on the left channel

**Comment by cehbab** [comment]
hmm.
Can you paste the output of the Channels,. BitsPerSample and SamplesPerSec please ??
And I re-upped 0.5e, because I rewrote part of it... simplified.

**Comment by cehbab** [comment]
I cannot get to state with my audio devices where I can test this properly, where I only have one channel from a stereo source, or one channel from a mono source where the sample rate can be matched for playback... dang,...
Ive tried dozens of things :)

**Comment by cehbab** [comment]
I think I figured out the issue, I wasn't copy it all, or any of the preprocessing I was trying to do..   I added a --zero-left and --zero-right and saw it was only affecting the first frame.. and not all the frames in the buffer, so I fixed that...
Hopefully it works now.. 0.5f

**Comment by GianlucaApollaro** [comment]
It works! A tiny little issue. --mono-to-stereo.exe -? does not give the usage instructions anymore

**Comment by cehbab** [comment]
Awesome, thanks for testing..
I made a stupid mistake in the usage and fixed it.
I deleted 0.5f and re-upped a new 0.5f..

The --capture-renderer is quite fun.. Ive been using it all day to push the audio from my speakers to all of my monitors at the same time :)

Cheers.

**Comment by GianlucaApollaro** [comment]
Now you got it working perfectly. I suggest to make a pull request so that it can be merged into this repository ToadKing's one. Thanks for all your work!

**Comment by cehbab** [comment]
I've updated it one last time, to get it to be in a state that ToadKing might accept a pull request.
To do that I reverted back to his default options, so you'd have to disable skipping first samples, and disable force mono to stereo to get what you want again....

Cheers

**Comment by cehbab** [comment]
You may be interested, I added sample rate conversion as well.
Cheers.

Oh and the pull request was denied, original author is not interested in testing or maintaining anymore :)
