### ISSUE TITLE
doesnt work when output device is anything else than 16bit 48KHz

### ISSUE THREAD

**Issue by T0biasCZe** [ToadKing/mono-to-stereo#12]
When you have output device output format set to anything else than 16bit 48KHz, and you try to run the app
it throws error
Error: IAudioClient::Initialize failed (output): hr = 0x88890008
Error: Thread aborted before starting to capture: hr = 0x88890008

**Comment by aczekajski** [comment]
I have encountered the same error. My output device is 24-bit 44100Hz.

**Comment by aczekajski** [comment]
I looked through the code but this is well too much for me to understand unfortunately... It looks like the `pwfx` that is passed to `pMMOutDevice->Activate` is just whatever sample rate input device had divided by two, so it's 96KHz / 2 = 48KHz which my output device doesn't support. However I have no idea what to do about it... resample on the fly I guess? I might be completely and utterly wrong about it tho ^^'

### Workaround that worked for me
I installed Voicemeeter (free, from VB-Audio), selected a `VoiceMeeter Input (VB-Audio VoiceMeeter VAIO)` as `--out-device` of mono-to-stereo, and in Voicemeeter set the "hardware out" to my actual output device.

**Comment by DragRedSim** [comment]
I had the same thing even with the audio format set to 16-bit, 48000khz. However, I was trying to run it while the default audio device it was trying to use was set to 5.1 surround audio; I changed the format to stereo and it came up fine.

**Comment by cehbab** [comment]
> I had the same thing even with the audio format set to 16-bit, 48000khz. However, I was trying to run it while the default audio device it was trying to use was set to 5.1 surround audio; I changed the format to stereo and it came up fine.

That's what I fixed in my fork of this...
I never encountered my output sound device defaulting to 24 or 16 bit, so I never fixed this..
I didn't fix the change in bits or samplerate.

**Comment by jefecker** [comment]
> > I had the same thing even with the audio format set to 16-bit, 48000khz. However, I was trying to run it while the default audio device it was trying to use was set to 5.1 surround audio; I changed the format to stereo and it came up fine.
> 
> That's what I fixed in my fork of this... I never encountered my output sound device defaulting to 24 or 16 bit, so I never fixed this.. I didn't fix the change in bits or samplerate.

I've tested your fork here now and it worked better than the original project. I actually don't know too much how it works, but in my case it seems like it's an issue in sample rate.
In the original project it shows up to me the same issue reported by @T0biasCZe, regardless whether I'm using VoiceMeeter or not, however in your fork it at least goes as following:

 Channels 2 -> 2
 BitsPerSample 32 -> 32
 SamplesPerSec 24000 -> 48000
Error: cannot convert between sample rates
Error: Thread aborted before starting to capture: hr = 0x8000ffff

Do you know some alternate way to solve it?

**Comment by cehbab** [comment]
Ive tried to fix different channel counts and different sample sizes, but not SamplesPerSec, its a rate thing and its a lot more complicated..  If you go into you sound settings for your device, can you change the sample rate there ?
Or if not, can you change it to something that can match a sample rate option of your output sound device, ie check both input and output.

![sound_settings](https://github.com/ToadKing/mono-to-stereo/assets/15166510/9d1ba20b-5d94-4233-98f6-c30ce29726be)

**Comment by jefecker** [comment]
> Ive tried to fix different channel counts and different sample sizes, but not SamplesPerSec, its a rate thing and its a lot more complicated.. If you go into you sound settings for your device, can you change the sample rate there ? Or if not, can you change it to something that can match a sample rate option of your output sound device, ie check both input and output.

Yeah, I forgot to talk about it, but yes, I can't change the sample rate of my recording device (16 bit and 48KHz is set as the only "option" available, with the selection function grayed out). The language I use in Windows is Portuguese, but I guess the screenshot in question is understandable.
<img width="347" alt="Captura de tela 2024-02-14 022812" src="https://github.com/ToadKing/mono-to-stereo/assets/115126223/bec42366-f840-422c-a0b7-0af948036839">
I've also tried now your tip on matching the sample rate of input and output (this one I can change), but nothing different happened.

**Comment by cehbab** [comment]
I've had a go, but I don't know!.
I found a third party library and tried to use it, but I can't get my audio devices to mismatch.
Well I can, but I can't make any sound in that input device. It doesn't crash when I go from 16000 -> 48000
So see how you go.
its version 0.5h in my forked repo.

Cheers.

Let me know how it goes.

**Comment by cehbab** [comment]
I had a try, but failed, I'll look into it some more.

**Comment by cehbab** [comment]
See how you go with 0.5h now..

If it does work for you, I figure I could go to the effort of building a static library for libsamplerate (not mine) and bundle it into the exe so its not separate..

I got sound finally with the following config.

<<   Realtek (Realtek(R) Audio)
>> BenQ BL2710 (NVIDIA High Definition Audio)
 Channels 6 -> 2
 BitsPerSample 32 -> 32
 SamplesPerSec 48000 -> 32000


I could capture from my hdmi, renderto my onboard realtek output one mono-to-stereo instance to upMix from stereo to 5.1 both 48000, and then downsample onboard stereo mixer, which when I captured from a render device, ie --capture-renderer, it picked up the 6 channels 48000 and rendered it to my monitor as stereo 32000

I assume if it can down sample rates, it can up sample rates, and my other logic of channel mixing is reliable..
I also tested 32 bit to 24, and 32 bit to 16, and I think I fluked it!. It appears it will work if its floats, but not too sure about plain PCM because of endianess.. we will see.. :)

Cheers
