### ISSUE TITLE
exe file instantly crashes when opening

### ISSUE THREAD

**Issue by Metalmarker2339** [ToadKing/mono-to-stereo#13]
It used to work, now it just doesn't

**Comment by supern64** [comment]
did your input device name change?

**Comment by Metalmarker2339** [comment]
No, i think it's not related to anything of the sort. I can't even open the exe file by itself, it just leads to instant crashing- Even  after deleting all my pc data it remained consisten so it's really odd. As i said, it USED to work, now it just does not

**Comment by supern64** [comment]
try opening it from the command line (as in type the command in the command line), you will see an error

this happened to me as well so we could be facing the same issue

**Comment by Metalmarker2339** [comment]
If you mean going to the directory,opening the cmd to that direvtory and
typing the exe file name i did it already and i got nothing, emptiness. If
i did something wrong then i shall try again when i am home

Il dom 8 ott 2023, 18:57 SuperN64 ***@***.***> ha scritto:

**Comment by supern64** [comment]
alright

**Comment by Metalmarker2339** [comment]
It seems to be working now! Thank you! i'll reply if i get the same problem ever again <3
