### ISSUE TITLE
FYI, the channels aren't swapped

### ISSUE THREAD

**Issue by marcan** [ToadKing/mono-to-stereo#2]
I figured this out later; the card returns the channels in the correct order, but with an offset to the data (the first sample is only the R channel).

R LR LR LR LR LR...

So the correct solution is to interpret the data as L-R pairs, and if the channels end up "swapped", do *not* swap them, but instead throw away two bytes at the beginning (one mono sample) and try again.

If you try to fix the swap by swapping channels, then you end up with a 1 sample phase offset between channels, which is incorrect and will introduce subtle stereo imaging issues and a comb filter effect if downsampled to mono.

**Comment by ToadKing** [comment]
Thanks for that info. Pushed a proper fix for the issue and removed the swap channels code since combining the two different paths would make things more complicated than they should be. This tool was mainly made for those MS2109 devices anyway.
