### ISSUE TITLE
Swapped audio channels

### ISSUE THREAD

**Issue by flextcg** [ToadKing/mono-to-stereo#4]
Hey there,

Your program is an absolute godsent, it's super easy to use, and gives a perfect audio quality. However I have a small little issue, which can be fixed in post, but if it's possible, it would be awesome to have it implemented into the build itself. 

The left and right audio channels are swapped sadly. Although I'm not sure if my capture card is the one that's faulty, or it's like this in general.

Thanks in advance!

**Comment by ToadKing** [comment]
Add the `--no-skip-first-sample` flag when you run the app. By default it skips the first sample so it works well with the MS2109 devices with that quirk.

**Comment by phourniner** [comment]
So the provided flag isn't working, I have it set up like so:
@start` "Mono to Stereo" /normal /min mono-to-stereo.exe --no-skip-first-sample --in-device "Digital Audio Interface (ShadowCast)"

The audio is still incorrect, even when restarting the .bat file. 

If I remove the flag, and restart, the audio will sometimes fix itself.
