### ISSUE TITLE
Error while trying to run the program

### ISSUE THREAD

**Issue by Alvyssy** [ToadKing/mono-to-stereo#8]
When I try to run the program and set my in/out device it outputs this error

Error: IPropertyStore::GetValue failed: hr = 0xe000020b
Error: CPrefs::CPrefs constructor failed: hr = 0xe000020b

I don't know what to do, it worked fine ever since and now it's like this

**Comment by Taxom** [comment]
Check the output device settings.
48KHz 16bit.
Try to register the output device clearly.
example: 
` "mono-to-stereo.exe" --in-device "HDMItoUSB (USB Digital Audio)" --out-device "CABLE-A Input (VB-Audio Cable A)"`
